version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
        "
    volumes:
      - .:/server
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - ./.env


volumes:
  postgres_data:
