version: '3.5'
services:
  api:
    build: .

    ports:
      - 8000:8000

    env_file:
      - ./.env
    
    command: >
      sh -c "
        python wait_for_it.py &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput --clear &&
        python manage.py runserver 0.0.0.0:8000
        "
    networks:
      - app-net
    volumes:
      - ./:/home/server
      - static-vol:/home/server/digi_say/static

    depends_on:
      - db
    
  db:
    image: postgres:latest
    networks:
      - app-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

networks:
  app-net:
volumes:
  static-vol: {}
  postgres_data: {}