# Generated by Django 4.2.6 on 2023-10-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
